config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products

  root 'pages#landing'

  get 'pages/buyerhome'

  get 'pages/sellerhome'

  get 'pages/buyerfaq'

  get 'pages/sellerfaq'

  get 'pages/tos'

  get 'pages/profile'

  get 'store/index'

  devise_for :users
  scope "/admin" do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer.html.erb
<div class="navbar navbar-default navbar-fixed-bottom">
  <p class="navbar-text pull-left">© 2016 Marketplace</p>
  <ul class="nav navbar-nav navbar-left">
    <li><%= link_to "Terms", pages_tos_url , target:'_blank'%></li>
    <li><%= link_to "Link", pages_tos_url , target:'_blank'%></li>
  </ul>

  <a href="#" class="navbar-btn btn-info btn pull-right">
  <span class="glyphicon glyphicon-star"></span> social</a>

</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Market</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <form class="navbar-form navbar-left">
          <div class="form-group has-feedback">
            <input type="text" class="form-control" placeholder="Search">
            <i class="glyphicon glyphicon-search form-control-feedback text-muted"></i>
          </div>
          <!-- button removed for cleaner UI, TEST in mobile view -->
          <!-- <button type="submit" class="btn btn-default">Go</button> -->
        </form>
        <li><a href="/pages/sellerhome">Seller Home</a></li>
        <li><a href="/store/index">Store</a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <% if user_signed_in? %>
          <!-- <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li> -->
        <% else %>
          <li><%= link_to('Login', new_user_session_path)  %></li>
          <li><%= link_to('Register', new_user_registration_path)  %></li>
        <% end %>

        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
            <%= link_to('Edit registration', edit_user_registration_path) %>
            </li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
          </ul>
        </li>
        <% else %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>